version: "3"

networks:
  web:
    external: true

services:
  metabase-db:
    image: postgres:11.5
    container_name: metabase-postgres
    restart: always
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - /data/metabase/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_USER=metabase
      - POSTGRES_DB=metabase
    networks:
      - web
    ports:
      - 5433:5432

  metabase:
    image: metabase/metabase:v0.33.4
    container_name: metabase-app
    restart: always
    networks:
      - web
    volumes:
      - /data/metabase/metabase-data:/metabase-data
    environment:
      - JAVA_TIMEZONE=Europe/Amsterdam
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=yourpassword
      - MB_DB_HOST=metabase-db
      - MB_ENCRYPTION_SECRET_KEY=yoursecret
    depends_on:
      - metabase-db
    labels:
      - traefik.backend=metabase
      - traefik.frontend.rule=Host:metabase.yourdomain
      - traefik.docker.network=web
      - traefik.port=3000