version: "3"
services:

  metabase-db:
    image: postgres:11.5
    container_name: metabase-postgres
    restart: always
    networks:
      - web
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - /data/metabase/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=somecomplexpassword
      - POSTGRES_USER=metabase
      - POSTGRES_DB=metabase
    ports:
      - 5433:5432

  metabase:
    image: metabase/metabase:v0.33.2
    container_name: metabase-app
    restart: always
    networks:
      - web
    volumes:
      - /data/metabase/metabase-data:/metabase-data
    environment:
      - JAVA_TIMEZONE=Europe/Amsterdam
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=somecomplexpassword
      - MB_DB_HOST=metabase-db
      - MB_ENCRYPTION_SECRET_KEY=somecomplexencryptionkey
    ports:
      - 3000:3000
    depends_on:
      - metabase-db
    labels:
      - traefik.enable=true
      - traefik.default.protocol=http
      - traefik.docker.network=web
      - traefik.backend=metabase
      - traefik.frontend.rule=Host:something.domain.com
      - traefik.port=3000
      - traefik.frontend.rateLimit.extractorFunc=client.ip
      - traefik.frontend.rateLimit.rateSet.r1.period=3s
      - traefik.frontend.rateLimit.rateSet.r1.average=50
      - traefik.frontend.rateLimit.rateSet.r1.burst=15

networks:
  web:
    external: true